security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 112358@Reg
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: s01.bientity.com
      username: root
      password: 112358@Reg
      database: admin
      port: 27017


  rabbitmq:
    host: s01.bientity.com
    port: 5672
    username: test1
    password: 112358@Reg
    virtual-host: /

server:
  context-path: /accounts
  port: 6000
