spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 2849923947
    driver-class-name: com.mysql.cj.jdbc.Driver
