spring:
  data:
    mongodb:
#      host: auth-mongodb
      host: s01.bientity.com
      username: root
#      password: ${MONGODB_PASSWORD}
      password: 112358@Reg
      database: admin
      port: 27017

  rabbitmq:
      host: s01.bientity.com
      port: 5672
      username: test1
      password: 112358@Reg
      virtual-host: /

server:
  context-path: /uaa
  port: 5000
